### ISSUE TITLE
Use of the "ID" field

### ISSUE THREAD

**Issue by hyperpac** [PhilSchwerttraeger/SIEMT#10]
What is the concept behind the "ID" field? Is this the (unique) primary key? If so, please hide or make it non-editable.

Does it in any way affect the sorting of either the category tags or the rows in general?

**Comment by PhilSchwerttraeger** [comment]
It's just the unique primary key, yes. And the parameter for initial sorting the table. Hiding it will not affect anything, I think. I am going to change that.

**Comment by PhilSchwerttraeger** [comment]
Is now hidden.

**Comment by hyperpac** [comment]
I think it also applies to the categories, doesn´t it?

**Comment by PhilSchwerttraeger** [comment]
Having control over the category IDs offers control over the order of the columns in the main table. You can even work with negative ids to create columns in front of already created. But if you are willing to lose that, I'll adjust that accordingly.

**Comment by hyperpac** [comment]
No change. Just wanted to know.
