### ISSUE TITLE
Analysis window broken when filtering table by search

### ISSUE THREAD

**Issue by hyperpac** [PhilSchwerttraeger/SIEMT#11]
![grafik](https://user-images.githubusercontent.com/28005681/41026861-e55207d4-6975-11e8-95b5-2a754b12e913.png)

And keeps being broken after removing the search string.

**Comment by hyperpac** [comment]
And now analysis is totally broken...

**Comment by PhilSchwerttraeger** [comment]
Broken widget after typing into search bar is fixed now. Though analysis calculation is disabled, because it is going to be connected to actual visible (filtered) table entries soon.

**Comment by hyperpac** [comment]
Checked and confirmed.
