### ISSUE TITLE
ID generation method

### ISSUE THREAD

**Issue by PhilSchwerttraeger** [PhilSchwerttraeger/SIEMT#5]
jfyi: Currently IDs are generated by selected the lowest free value. When there are gaps in the database these will be stuffed with the next new entries. This can be changed to a strictly incrementing counter. Not sure if that would bring any benefit.

**Comment by hyperpac** [comment]
Plz change to stricly incremental.

**Comment by PhilSchwerttraeger** [comment]
Changed.
